/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "mlmodel_online_project_constants.h"

namespace mlmodelserver {

const mlmodel_online_projectConstants g_mlmodel_online_project_constants;

mlmodel_online_projectConstants::mlmodel_online_projectConstants() {
}

} // namespace

