/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef caffe_server_CONSTANTS_H
#define caffe_server_CONSTANTS_H

#include "caffe_server_types.h"

namespace caffeserver {

class caffe_serverConstants {
 public:
  caffe_serverConstants();

};

extern const caffe_serverConstants g_caffe_server_constants;

} // namespace

#endif
