/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "caffe_server_constants.h"

namespace caffeserver {

const caffe_serverConstants g_caffe_server_constants;

caffe_serverConstants::caffe_serverConstants() {
}

} // namespace

