/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef mlmodel_online_project_CONSTANTS_H
#define mlmodel_online_project_CONSTANTS_H

#include "mlmodel_online_project_types.h"

namespace modelpro {

class mlmodel_online_projectConstants {
 public:
  mlmodel_online_projectConstants();

};

extern const mlmodel_online_projectConstants g_mlmodel_online_project_constants;

} // namespace

#endif
